name: Manuel Oraxen Derleyici

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Java 21 Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle İzinlerini Ayarla
        run: chmod +x gradlew

      - name: Eklentiyi Derle (ShadowJar)
        run: ./gradlew shadowJar

      - name: Klasör İçeriğini Listele (Hata Ayıklama)
        run: |
          echo "=== build/libs klasörünün içeriği ==="
          ls -R build/libs/ || echo "Klasör bulunamadı!"

      - name: Hazır .JAR Dosyasını Teslim Et (Genişletilmiş Yol)
        uses: actions/upload-artifact@v4
        with:
          name: Oraxen-Bedava-Premium
          path: |
            build/libs/*.jar
            **/build/libs/*.jar
