name: Manuel Oraxen Derleyici

on:
  workflow_dispatch: # Bu satır sayesinde butona basıp elle tetikleyeceğiz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Java 21 Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle İzinlerini Ayarla
        run: chmod +x gradlew

      - name: Eklentiyi Derle (ShadowJar)
        run: ./gradlew shadowJar

      - name: Hazır .JAR Dosyasını Teslim Et
        uses: actions/upload-artifact@v4
        with:
          name: Oraxen-Bedava-Premium
          path: build/libs/*-all.jar
